[package]
name = "phext-shell"
version = "0.1.7"
authors = ["Will Bickford <wbic16@gmail.com>"]
description = "A phext-native implementation of an operating system shell"
homepage = "https://phext.io/"
license = "MIT"
edition = "2021"

[dependencies]
libphext = "0.1.2"